kind = "web"
previewPath = "/eyeways-mergesafe"
title = "EyewaysMergeSafeServer"
version = "1.0.0"

[[services]]
localPort = 5000
name = "EyewaysMergeSafeServer"
paths = ["/eyeways-mergesafe"]

[services.development]
run = "PORT=5000 dotnet run --project artifacts/eyeways-mergesafe/EyewaysMergeSafeServer/EyewaysMergeSafeServer.csproj"

[services.production]

[services.production.run]
args = ["dotnet", "artifacts/eyeways-mergesafe/EyewaysMergeSafeServer/bin/Release/net8.0/EyewaysMergeSafeServer.dll"]

[services.production.run.env]
PORT = "5000"
